### ISSUE TITLE
The word “ready” is not highlighted in the search results.

### ISSUE THREAD

**Issue by 23lizards** [FreeFeed/freefeed-react-client#792]
**Steps to reproduce**
1. https://freefeed.net/search?qs=ready%20player%20one or https://freefeed.net/search?qs=ready or any other search request containing the word “ready”.

**Expected result**
“Ready” is highlighted in the search results.

**Actual result**
“Ready” is not highlighted in the search results.

**Additional info**
Frontend used: https://freefeed.net
This issue does not depend on the OS/browser.
Please share the root cause after you guys fix the issue; I’m goddamn curious! :)

**Screenshots**
“ready player one”:
![freefeed-search-ready-player-one](https://user-images.githubusercontent.com/7023583/39795277-c5dcd8b8-5357-11e8-9b50-71a9c1996ca7.png)

“ready”:
![freefeed-search-ready-2](https://user-images.githubusercontent.com/7023583/39795363-556f021c-5358-11e8-8ac7-7490fcc6cd35.png)

┆Issue is synchronized with this [Trello card](https://trello.com/c/ci8cUBRF)

**Comment by indeyets** [comment]
The problem is, that our usage of [porter-stemmer](https://github.com/jedp/porter-stemmer) is incorrect.

We process search terms thru stemmer and build regexes from "stemmed" terms. Then we apply these regexes to the text. This would be fine if stemmer's results would always be substrings of words. They're not.

To be closer to ths issue: stemmed term for "ready" is "readi", regex we build is `/(^|[^a-z])(readi[a-z]*)/i`, but this regex wouldn't find anything in text.

The proper usage is to process words of text by stemmer too and math stemmed words against stemmed query terms
