### ISSUE TITLE
Foldable menu on small screens

### ISSUE THREAD

**Issue by dandaka** [FreeFeed/freefeed-react-client#99]
### Right now ###

Right sidebar menu goes under news feed on small screens. It makes no sense and counterintuitive.

### Should be ###

1. Menu folds into "hamburger" icon on small screens http://take.ms/pb9XX
2. Hamburger unfolds on click to menu on top of news feed (or moving it down)

**Comment by urbansheep** [comment]
Details:

1. Sidebar should become hidden when viewport is less than 760px wide.
2. When sidebar is hidden there should appear a navigation “hamburger” icon button (three horizontal bars, http://fortawesome.github.io/Font-Awesome/icon/bars/) in the top right corner (size of 32px, padding 10-16px).
3. This icon should stick to the screen and stay at the same screen position even while content is scrolled.
4. On click on the menu icon sidebar should appear overlaid on top of the main content column, with current contents of the sidebar. It should be scrollable independently of the main content. When sidebar is scrolled, menu icon should still be seen fixed in the top right corner, menu icon should not scroll away with sidebar contents.
5. Sidebar is non-transparent, but content behind it may be shaded by the transparent black overlay.
6. Sidebar width is 100% when viewport width is 320px or less. Sidebar width should be fixed at 275px if viewport width is larger than 320px.

![frf-sidebar-1-closed](https://cloud.githubusercontent.com/assets/1756417/11391498/f2421eb0-9363-11e5-86c4-675ab2f9c227.png)
![frf-sidebar-2-open](https://cloud.githubusercontent.com/assets/1756417/11391499/f26bdb6a-9363-11e5-8258-58b534340e60.png)
![frf-sidebar-2-scrolled](https://cloud.githubusercontent.com/assets/1756417/11391500/f26d6cdc-9363-11e5-904c-c0c0105c15ad.png)

**Comment by indeyets** [comment]
closed via #175
